apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.name" . }}-deployment
  namespace: {{ include  "my-app.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "my-app.name" . }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "my-app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "my-app.name" . }}
    spec:
      containers:
      - name: ghost
        image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
        env:
          - name: NODE_ENV
            value: {{ .Values.app.env.NODE_ENV }}
        ports:
        - name: ghost
          containerPort: {{ .Values.app.port }}
