apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.name" . }}-svc
  namespace: {{ include  "my-app.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "my-app.name" . }}
    jobLabel: {{ include "my-app.name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "my-app.name" . }}
  ports:
    - name: {{ include "my-app.name" . }}-port
      protocol: TCP
      port: 80
      targetPort: {{ .Values.app.port }}